.TH cat 1 Feb-24-2011 cupucupu
.SH NAME
.IP
cat - Read text file(s) and print on the standard output
.PP
.SH SYNOPSIS
.IP
.B cat
[
.B filename
]
.BR
.IP
.B cat
[
.B file1
] [
.B file2
] ...
.PP
.SH DESCRIPTIONS
.IP
Cat command is used to reading text file and displaying the result to the screen.
.PP
.SH OPTIONS
.IP
Cat simulation vesion 0.01 come with no options.
.PP
.SH EXAMPLE
.IP
For reading text1.txt, you can use these command
.PP
.IP
.B cat
.I text1.txt
.PP
.IP
or if you want to read more then one text file, yo can use command like this
.PP
.IP
.B cat
.I text1.txt text2.txt
.PP
.SH BUGS
.IP
cat simulation version 0.01 only can read
.I text
file.
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
.BR
.IP
.IP
Torbjorn Granlund
.BR
.IP
.IP
Richard M. Stallman
.PP
.SH SEE ALSO
.IP
-
