.TH cd 1 Feb-24-2011 cupucupu
.SH NAME
.IP
cd - Change current working directori
.PP
.SH SYNOPSIS
.IP
.B
cd
[
.I dirname
]
.PP
.SH DESCRIPTIONS
.IP
.B cd
command will change current working directory to
.I dirname
.
.PP
.IP
If the
.B cd
command not given some argument, they will try to change the working directory to user home.
.PP
.SH OPTIONS
.IP
No options available in version 0.01. Just run
.B cd
or
.B cd
[
.I dirname
]
.PP
.SH EXAMPLE
.IP
.B cd
- Will change current working directory to the user home.
.PP
.IP
That will be same effect if you run
.B cd HOME
(
.I remember, the HOME argument is case sensitive. HOME and home is different.
) or
.B cd ~
.
.PP
.IP
.B cd ..
- will be back one step to the parent directory.
.PP
.IP
If the destination directory have a space in the name, you need to use single quote (
.B ''
) or double quote (
.B ""
) in the prefix and sufix
.I dirname
.
.PP
.IP
Example:
.BR
.IP
.IP
.B cd "dir 1"
.BR
.IP
or
.BR
.IP
.IP
.B cd 'dir 1'
.PP
.SH BUGS
.IP
In version 0.01, the cd command will not work with root symbol "
.B /
" (e.g: cd / ). So, you need to bring two doted in the prefix if you want to go to root directory (
.I yeah, that run like cd ..
).
.PP
.IP
And, the home symbol like this "
.B ~/
" an forward symbol
.B -
.
.PP
.IP
The
.B cd
command will not work with that symbols.
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: ?
.PP
.SH SEE ALSO
.IP
pwd(1)
