.TH clear 1 Feb-24-2011 cupucupu
.SH NAME
.IP
clear - Clear the terminal screen
.PP
.SH SYNOPSIS
.IP
clear
.PP
.SH DESCRIPTIONS
.IP
clear your terminal screen if this is possible.
.PP
.SH OPTIONS
.IP
clear version 0.01 come with no options.
.PP
.SH BUGS
.IP
Not yet known
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: ?
.PP
.SH SEE ALSO
.IP
-
