.TH cp 1 Feb-24-2011 cupucupu
.SH NAME
.IP
cp - Copy file and directory
.PP
.SH SYNOPSIS
.IP
.B cp
[
.B file1
] [
.B file2
]
.BR
.IP
.B cp
[
.B filename
] [
.B dirname
]
.PP
.SH DESCRIPTIONS
.IP
Copying
.I source
file to
.I destination
folder or copying
.I old file
to
.I new file
.
.PP
.SH OPTIONS
.IP
cp simulation version 0.01 come with no options.
.PP
.SH EXAMPLE
.IP
.B cp
[
.B old file
] [
.B new file
] - Copying
.I old file
to
.I new file
.
.BR
.IP
.B cp
[
.B file name
] [
.B dir name
] - Copying
.I file name
into
.I dir name
.
.BR
.IP
.B cp
[
.B dir1
] [
.B dir2
] - Copying
.I dir1
into
.I dir2
.
.PP
.SH BUGS
.IP
cp simulation version 0.01 only can copying file and empty directory. If copying non empty directory, error messages will be displayed on the screen.
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
.BR
.IP
.IP
Torbjorn Granlund
.BR
.IP
.IP
David MacKenzie
.BR
.IP
.IP
Jim Meyering
.PP
.SH SEE ALSO
.IP
-
