.TH date 1 Feb-25-2011 cupucupu
.SH NAME
.IP
date - Print the system date and time
.PP
.SH SYNOPSIS
.IP
.B date
.PP
.SH DESCRIPTIONS
.IP
Display the current date and time of the system.
.PP
.SH OPTIONS
.IP
.B date
simulation version 0.01 come with no options.
.PP
.SH BUGS
.IP
Dont known for now
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: David MacKenzie.
