.TH help 1 Feb-25-2011 cupucupu
.SH NAME
.IP
help - print the list of commands.
.PP
.SH SYNOPSIS
.IP
help
.BR
.IP
help [
.I --less
]
.PP
.SH DESCRIPTIONS
.IP
Help simulation is command to print a list of commands.
Here you will see the command with parameter if needed. But without
any descriptions.
.PP
.SH OPTIONS
.IP
.B help --less
- With
.I --less
option, the help command will try to print the output in loseless mode.
.PP
.SH EXAMPLE
.IP
.B help
- Will print the output in fast mode. You need to scrollup the screen
to see the first line.
.BR
.IP
.B help --less
- Will print the output in loseless mode. You can read word by word
with this option and no need to scrollup the screen.
.PP
.SH BUGS
.IP
Not known yet
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: ?
.PP
.SH SEE ALSO
.IP
man(1)
