.TH hostname 1 Feb-24-2011 cupucupu
.SH NAME
.IP
hostname - Show host name
.PP
.SH SYNOPSIS
.IP
hostname
.PP
.SH DESCRIPTIONS
.IP
hostname is used to display current host name.
.PP
.SH OPTIONS
.IP
hostname version 0.01 come with no options.
.PP
.SH BUGS
.IP
Not yet found
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
.BR
.IP
Peter Tobias <
.I tobias@et-inf.fho-emden.de
>
.BR
.IP
Bernd Eckenfels <
.I net-tools@lina.inka.de
>
.BR
.IP
Steve Whitehouse <
.I SteveW@ACM.org
>
