.TH less 1 Feb-25-2011 cupucupu
.SH NAME
.IP
less - Opposite of more
.PP
.SH SYNOPSIS
.IP
.B less
.I filename
.PP
.SH DESCRIPTIONS
.IP
Less is a program similar to more(1), but which allows backward  movement in the file as well as forward movement
.PP
.SH OPTIONS
.IP
less simulation version 0.01 come with no options.
.PP
.SH EXAMPLE
.IP
.B less
.I filename
- Read and print the output to the terminal screen.
.PP
.SH BUGS
.IP
Only text can handled by less simulation version 0.01
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: Mark Nudelman <
.I markn@greenwoodsoftware.com
>
.PP
.SH SEE ALSO
.IP
-
