.TH ls 1 Feb-25-2011 cupucupu
.SH NAME
.IP
ls - list directory contents
.PP
.SH SYNOPSIS
.IP
.B ls
[
.I dirname
]
.BR
.IP
.B ls
[
.I filename
]
.PP
.SH DESCRIPTIONS
.IP
List information about the file or directory (
.I the current directory by default
).
.PP
.SH OPTIONS
.IP
ls simulation version 0.01 come with no options.
.PP
.SH EXAMPLE
.IP
.B ls filename
.BR
.IP
.B ls dirname
.BR
.IP
or
.BR
.IP
.B ls file1 file2 ...
.BR
.IP
.B ls dir1 dir2 ...
.PP
.SH BUGS
.IP
ls simulation version 0.01 can not read the root symbol "
.B /
". And the
.I home
symbol (
.B ~
,
.B ~/
or
.B HOME
)
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: Richard M. Stallman and David MacKenzie.
.PP
.SH SEE ALSO
.IP
-
