.TH man 1 Feb-25-2011 cupucupu
.SH NAME
.IP
man - Format and display on-line manual page
.PP
.SH SYNOPSIS
.IP
.B man
[
.I command_name
]
.PP
.SH DESCRIPTIONS
.IP
The
.B man
command is use to formatting and displaying the on-line manual page of installed programs.
.PP
.SH OPTIONS
.IP
man simulation version 0.01 come with no options.
.PP
.SH EXAMPLE
.IP
.B man
.I man
.BR
.IP
For displaying manual page of
.I man
program.
.PP
.SH BUGS
.IP
This is a clone of man program on Unix. And called man simulation. This clone is only can processed a very basic syntax of
.I groff
. So, if you writing manual page with more syntax, they will be ignored and not be translated.
.PP
.IP
See /usr/doc/man-0.01/man-howto for accepted syntax.
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: John W. Eaton was the original author of
.B man
. Zeyd M. Ben-Halim released man 1.2, and Andries Brouwer followed up with version 1.3 thru 1.5p. Fedelico Lucifredi <
.I lucifredi@acm.org
> is current maintainer.
.PP
.SH SEE ALSO
.IP
help(1)
