.TH mime 1 15-March-2011 cupucupu
.SH NAME
.IP
mime - File storage for file types
.PP
.SH SYNOPSIS
.IP
See /usr/doc/mime-0.01/readme-compressed.txt
.PP
.SH DESCRIPTIONS
.IP
Mime simulation is a file for storing list of any file types.
.PP
.IP
This file called compressed.types and put in /usr/share/mime
.BR
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: N/A
.BR
.SH SEE ALSO
.IP
compressed.types(1)
