.TH mkdir 1 Feb-26-2011 cupucupu
.SH NAME
.IP
mkdir - Create directory
.PP
.SH SYNOPSIS
.IP
.B mkdir
.I dirname
.BR
.IP
.B mkdir
.I dir1 dir2 ...
.PP
.SH DESCRIPTIONS
.IP
Create a new directory
.PP
.SH OPTIONS
.IP
mkdir simulation version 0.01 come with no options.
.PP
.SH BUGS
.IP
Not known yet
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
Written by David MacKenzie.
