.TH mv 1 Feb-26-2011 cupucupu
.SH NAME
.IP
mv - move or rename file and directory
.PP
.SH SYNOPSIS
.IP
.B mv
.I oldfile newfile
.BR
.IP
.B mv
.I surce destination
.PP
.SH DESCRIPTIONS
.IP
mv simulation is a command that uses for moving or renaming file and directory.
.PP
.SH OPTIONS
.IP
mv simulation version 0.01 come with no options.
.PP
.SH BUGS
.IP
Can not move if directory is not empty
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
Written by Mike Parker, David MacKenzie, and Jim Meyering.
