.TH nano 1 Feb-26-2011 cupucupu
.SH NAME
.IP
nano - nano a simple text editor
.PP
.SH SYNOPSIS
.IP
.B nano
.BR
.IP
.B nano
.I filename
.BR
.IP
.B nano
.I newfilename
.PP
.SH DESCRIPTIONS
.IP
Nano simulation is a simple text editor written for limit.
.PP
.SH OPTIONS
.IP
nano simulation version 0.01 come with no options.
.PP
.SH BUGS
.IP
Not known yet
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
Chris Allegretta <
.I chrisa@asty.org
>, et al (
.I see AUTHORS and  THANKS  for details
).
