.TH pwd 1 Feb-24-2011 cupucupu
.SH NAME
.IP
pwd - Print name of current working directory
.PP
.SH SYNOPSIS
.IP
pwd
.PP
.SH DESCRIPTIONS
.IP
pwd command used for displaying full name of current working directory.
.PP
.SH OPTIONS
.IP
In this version (
.I 0.01
), the pwd command come with no options.
.PP
.SH BUGS
.IP
Not yet found.
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author is: Jim Meyering
.PP
.SH SEE ALSO
.IP
-
