.TH rm 1 Feb-26-2011 cupucupu
.SH NAME
.IP
rm - remove one or more file
.PP
.SH SYNOPSIS
.IP
.B rm
[
.B option
]
.I filename
.BR
.IP
.B rm
[
.B option
]
.I file1 file2 ...
.PP
.SH DESCRIPTIONS
.IP
rm simulation is a command for removing one or more file.
.PP
.SH OPTIONS
.IP
.B -v
- Verbose mode
.PP
.SH BUGS
.IP
Can not remove directory recursivly
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
Written  by  Paul  Rubin, David MacKenzie, Richard M. Stallman, and Jim Meyering.
