.TH rmdir 1 Feb-26-2011 cupucupu
.SH NAME
.IP
rmdir - Remove directory
.PP
.SH SYNOPSIS
.IP
.B rmdir
[
.B option
]
.I dirname
.BR
.IP
.B rmdir
[
.B option
]
.I dir1 dir2 ...
.PP
.SH DESCRIPTIONS
.IP
rmdir used to removing one or more empty directory
.PP
.SH OPTIONS
.IP
.B -v
- Verbose mode
.PP
.SH BUGS
.IP
Not known yet
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
Written by David MacKenzie.
