.TH whoami 1 Feb-24-2011 cupucupu
.SH NAME
.IP
whoami - Print effective userid
.PP
.SH SYNOPSIS
.IP
whoami
.PP
.SH DESCRIPTIONS
.IP
Print the usename assosiated with the current effective user ID.
.PP
.SH OPTIONS
.IP
whoami version 0.01 come with no options.
.PP
.SH BUGS
.IP
Not yet found.
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
Original author: Richard Mlynarik
.PP
.SH SEE ALSO
.IP
-
