.TH halt 8 Feb-26-2011 cupucupu
.SH NAME
.IP
halt, reboot - stop the system
.PP
.SH SYNOPSIS
.IP
.B halt
.BR
.IP
.B reboot
.PP
.SH DESCRIPTIONS
.IP
.B Halt
notes that the system is being brought down in the file
.I /var/log/wtmp
, and then either tells the  kernel  to  halt, reboot or poweroff the system.
.PP
.SH OPTIONS
.IP
halt simulation version 0.01 come with no options.
.PP
.SH BUGS
.IP
Not known yet
.PP
.SH AUTHOR
.IP
cupucupu <
.I cupu.cupuh@yahoo.co.id
>
.PP
.IP
.B Original author:
Miquel van Smoorenburg,
.I miquels@cistron.nl
.PP
.SH SEE ALSO
.IP
halt(8)
